# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NzJjYjJlYzNjNjk5NGYwNjRiNjkyMzNiZTYzOGEzYTE2MmYxNzU3ZGUzMTNmMmIyYWY4YjRkYzZiMjJjMDhlMjQyYjBhZGVjYmRlMmYyN2I3OTM2MDgwYjM0NGRjYzUzNWIyNDhjOTAxMDhmYTRhMDFiZjNkNDIyZDcxMWRmMTM=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
